#-------------------------------
# General Site Settings

title: Needful things | Blog 
description: Ein Blog für diverse Inhalte
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://d.bueltmann.ch" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author: Needful things
author-name:   Needful things
author-avatar: ILoveCoffee-quadrat.png


#-------------------------------
# Contact links
#facebook:  https://facebook.com/ # Add your Facebook handle
#twitter:   https://twitter.com/ # Add your Facebook handle
#instagram: https://www.instagram.com/ # Add your Facebook handle
#pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: d-bueltmann-ch # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.

#-------------------------------
# widget-newsletter
widget-newsletter: false # To enable the instafeed, use the value true. To turn off use the value false.

#-------------------------------
# widget-social
widget-social: false # To enable the widget-social, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
